# Generated by Django 3.0.5 on 2020-04-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("books", "0002_book_in_print")]

    operations = [
        migrations.CreateModel(
            name="Consortium",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("marketcap", models.IntegerField(default=9999999)),
            ],
        ),
        migrations.AddField(
            model_name="publisher",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.Consortium",
            ),
        ),
    ]
